# Generated by Django 4.2.13 on 2026-03-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_bmi_score', models.IntegerField(default=0)),
                ('must_weight_loss_score', models.IntegerField(default=0)),
                ('must_acute_score', models.IntegerField(default=0)),
                ('must_total_score', models.IntegerField(default=0)),
                ('must_risk', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('must_explanation', models.TextField(blank=True)),
                ('ml_probability', models.FloatField(blank=True, null=True)),
                ('ml_risk_flag', models.BooleanField(default=False)),
                ('ml_top_factors', models.JSONField(default=list)),
                ('ml_explanation', models.TextField(blank=True)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('alert_level', models.CharField(default='NONE', max_length=15)),
                ('alert_source', models.CharField(choices=[('MUST', 'MUST'), ('ML', 'ML'), ('BOTH', 'Both'), ('MUST_MODERATE', 'MUST Moderate'), ('NONE', 'None')], default='NONE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='patients.consultation')),
            ],
        ),
    ]
